/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */
public class AdminBlock extends javax.swing.JFrame {

    /**
     * Creates new form Four
     */
    public AdminBlock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new java.awt.Button();
        roomallotment = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchstudent1 = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        checkcomplain1 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(255, 204, 204));
        logout.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logout.setLabel("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 270, 40));

        roomallotment.setBackground(new java.awt.Color(255, 204, 204));
        roomallotment.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        roomallotment.setLabel("Room Allotment");
        roomallotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomallotmentActionPerformed(evt);
            }
        });
        jPanel1.add(roomallotment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 270, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Search_52px_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Dog_House_52px_1.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 40));

        searchstudent1.setBackground(new java.awt.Color(255, 204, 204));
        searchstudent1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        searchstudent1.setLabel("Search Student");
        searchstudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchstudent1ActionPerformed(evt);
            }
        });
        jPanel1.add(searchstudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 270, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Workspace_52px_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 50, 40));

        checkcomplain1.setBackground(new java.awt.Color(255, 204, 204));
        checkcomplain1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        checkcomplain1.setLabel("Check Complain");
        checkcomplain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcomplain1ActionPerformed(evt);
            }
        });
        jPanel1.add(checkcomplain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 270, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Logout_Rounded_Left_52px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 460, 610));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 80)); // NOI18N
        jLabel3.setText("Administrative Block");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 530, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/adminphoto.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomallotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomallotmentActionPerformed
        // TODO add your handling code here:
        SroomAllot sa = new SroomAllot();
        sa.setVisible(true);
        dispose();
    }//GEN-LAST:event_roomallotmentActionPerformed

    private void searchstudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchstudent1ActionPerformed
        // TODO add your handling code here:
        Searching sc = new Searching();
        sc.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchstudent1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Information im = new Information();
        im.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

        PreparedStatement pstmt = null;
        ResultSet rs = null;
        
    private void checkcomplain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcomplain1ActionPerformed
        // TODO add your handling code here:
        ComplainCheck cc = new ComplainCheck();
        int count=0;
         try
        {
            MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
            pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo");
            rs = pstmt.executeQuery();
            while(rs.next())
            {
                if(rs.getString("Complain")!=null)
                {
                    count++;
                    if(count==1)
                    {
                        cc.regnoTextFieldres1.setText(rs.getString("Registration_No"));
                        cc.roomnoTextFieldres1.setText(rs.getString("Room_No"));
                        cc.hostelTextFieldres1.setText(rs.getString("Hostel_Name"));
                        cc.emailTextFieldres1.setText(rs.getString("Complain"));
                    }
                    if(count==2)
                    {
                        cc.regnoTextFieldres2.setText(rs.getString("Registration_No"));
                        cc.roomnoTextFieldres2.setText(rs.getString("Room_No"));
                        cc.hostelTextFieldres2.setText(rs.getString("Hostel_Name"));
                        cc.emailTextFieldres2.setText(rs.getString("Complain"));
                    }
                    if(count==3)
                    {
                        cc.regnoTextFieldres3.setText(rs.getString("Registration_No"));
                        cc.roomnoTextFieldres3.setText(rs.getString("Room_No"));
                        cc.hostelTextFieldres3.setText(rs.getString("Hostel_Name"));
                        cc.emailTextFieldres3.setText(rs.getString("Complain"));
                    }
                    if(count==4)
                    {
                        cc.regnoTextFieldres4.setText(rs.getString("Registration_No"));
                        cc.roomnoTextFieldres4.setText(rs.getString("Room_No"));
                        cc.hostelTextFieldres4.setText(rs.getString("Hostel_Name"));
                        cc.emailTextFieldres4.setText(rs.getString("Complain"));
                    }
                }
            }
            cc.setVisible(true);
        }
         catch(SQLException e)
         {
             System.out.println(e);
         }
             
    }//GEN-LAST:event_checkcomplain1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBlock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button checkcomplain1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Button logout;
    private java.awt.Button roomallotment;
    private java.awt.Button searchstudent1;
    // End of variables declaration//GEN-END:variables
}
