/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

/**
 *
 * @author hp
 */
public class ComplainCheck extends javax.swing.JFrame {

    /**
     * Creates new form ComplainCheck
     */
    public ComplainCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roomnoTextFieldres1 = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        regnoTextFieldres1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        hostelTextFieldres1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        emailTextFieldres1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        roomnoTextFieldres2 = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        regnoTextFieldres2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        hostelTextFieldres2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        emailTextFieldres2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        regnoTextFieldres3 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        hostelTextFieldres3 = new javax.swing.JTextField();
        emailTextFieldres3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        roomnoTextFieldres3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        regnoTextFieldres4 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        hostelTextFieldres4 = new javax.swing.JTextField();
        emailTextFieldres4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        roomnoTextFieldres4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        regnoTextFieldres5 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        hostelTextFieldres5 = new javax.swing.JTextField();
        emailTextFieldres5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        roomnoTextFieldres5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Complaint Check");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 400, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Room No.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, 30));

        roomnoTextFieldres1.setBackground(new java.awt.Color(0, 0, 51));
        roomnoTextFieldres1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnoTextFieldres1.setForeground(new java.awt.Color(153, 255, 255));
        roomnoTextFieldres1.setBorder(null);
        roomnoTextFieldres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoTextFieldres1ActionPerformed(evt);
            }
        });
        jPanel1.add(roomnoTextFieldres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 60, 30));
        jPanel1.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 50, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Reg. No.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 110, 30));

        regnoTextFieldres1.setBackground(new java.awt.Color(0, 0, 51));
        regnoTextFieldres1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regnoTextFieldres1.setForeground(new java.awt.Color(153, 255, 255));
        regnoTextFieldres1.setBorder(null);
        regnoTextFieldres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextFieldres1ActionPerformed(evt);
            }
        });
        jPanel1.add(regnoTextFieldres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Hostel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, 30));

        hostelTextFieldres1.setBackground(new java.awt.Color(0, 0, 51));
        hostelTextFieldres1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostelTextFieldres1.setForeground(new java.awt.Color(153, 255, 255));
        hostelTextFieldres1.setBorder(null);
        hostelTextFieldres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelTextFieldres1ActionPerformed(evt);
            }
        });
        jPanel1.add(hostelTextFieldres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 100, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 110, 10));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 153, 51));
        jLabel32.setText("Complaint");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 110, 30));

        emailTextFieldres1.setBackground(new java.awt.Color(0, 0, 51));
        emailTextFieldres1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailTextFieldres1.setForeground(new java.awt.Color(153, 255, 255));
        emailTextFieldres1.setBorder(null);
        emailTextFieldres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldres1ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextFieldres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 300, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 270, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Room No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 110, 30));

        roomnoTextFieldres2.setBackground(new java.awt.Color(0, 0, 51));
        roomnoTextFieldres2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnoTextFieldres2.setForeground(new java.awt.Color(153, 255, 255));
        roomnoTextFieldres2.setBorder(null);
        roomnoTextFieldres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoTextFieldres2ActionPerformed(evt);
            }
        });
        jPanel1.add(roomnoTextFieldres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 60, 30));
        jPanel1.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("Reg. No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, 30));

        regnoTextFieldres2.setBackground(new java.awt.Color(0, 0, 51));
        regnoTextFieldres2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regnoTextFieldres2.setForeground(new java.awt.Color(153, 255, 255));
        regnoTextFieldres2.setBorder(null);
        regnoTextFieldres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextFieldres2ActionPerformed(evt);
            }
        });
        jPanel1.add(regnoTextFieldres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Hostel");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 80, 30));

        hostelTextFieldres2.setBackground(new java.awt.Color(0, 0, 51));
        hostelTextFieldres2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostelTextFieldres2.setForeground(new java.awt.Color(153, 255, 255));
        hostelTextFieldres2.setBorder(null);
        hostelTextFieldres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelTextFieldres2ActionPerformed(evt);
            }
        });
        jPanel1.add(hostelTextFieldres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 100, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 110, 10));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 153, 51));
        jLabel33.setText("Complaint");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 110, 30));

        emailTextFieldres2.setBackground(new java.awt.Color(0, 0, 51));
        emailTextFieldres2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailTextFieldres2.setForeground(new java.awt.Color(153, 255, 255));
        emailTextFieldres2.setBorder(null);
        emailTextFieldres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldres2ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextFieldres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 300, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 270, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 110, 10));

        regnoTextFieldres3.setBackground(new java.awt.Color(0, 0, 51));
        regnoTextFieldres3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regnoTextFieldres3.setForeground(new java.awt.Color(153, 255, 255));
        regnoTextFieldres3.setBorder(null);
        regnoTextFieldres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextFieldres3ActionPerformed(evt);
            }
        });
        jPanel1.add(regnoTextFieldres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 110, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText("Hostel");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 80, 30));

        hostelTextFieldres3.setBackground(new java.awt.Color(0, 0, 51));
        hostelTextFieldres3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostelTextFieldres3.setForeground(new java.awt.Color(153, 255, 255));
        hostelTextFieldres3.setBorder(null);
        hostelTextFieldres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelTextFieldres3ActionPerformed(evt);
            }
        });
        jPanel1.add(hostelTextFieldres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 100, 30));

        emailTextFieldres3.setBackground(new java.awt.Color(0, 0, 51));
        emailTextFieldres3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailTextFieldres3.setForeground(new java.awt.Color(153, 255, 255));
        emailTextFieldres3.setBorder(null);
        emailTextFieldres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldres3ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextFieldres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 300, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("Reg. No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 110, 30));

        roomnoTextFieldres3.setBackground(new java.awt.Color(0, 0, 51));
        roomnoTextFieldres3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnoTextFieldres3.setForeground(new java.awt.Color(153, 255, 255));
        roomnoTextFieldres3.setBorder(null);
        roomnoTextFieldres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoTextFieldres3ActionPerformed(evt);
            }
        });
        jPanel1.add(roomnoTextFieldres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 51));
        jLabel10.setText("Room No.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, 30));
        jPanel1.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 50, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 270, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 153, 51));
        jLabel34.setText("Complaint");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 110, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 110, 10));

        regnoTextFieldres4.setBackground(new java.awt.Color(0, 0, 51));
        regnoTextFieldres4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regnoTextFieldres4.setForeground(new java.awt.Color(153, 255, 255));
        regnoTextFieldres4.setBorder(null);
        regnoTextFieldres4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextFieldres4ActionPerformed(evt);
            }
        });
        jPanel1.add(regnoTextFieldres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 110, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 110, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 51));
        jLabel11.setText("Hostel");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 80, 30));

        hostelTextFieldres4.setBackground(new java.awt.Color(0, 0, 51));
        hostelTextFieldres4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostelTextFieldres4.setForeground(new java.awt.Color(153, 255, 255));
        hostelTextFieldres4.setBorder(null);
        hostelTextFieldres4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelTextFieldres4ActionPerformed(evt);
            }
        });
        jPanel1.add(hostelTextFieldres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 100, 30));

        emailTextFieldres4.setBackground(new java.awt.Color(0, 0, 51));
        emailTextFieldres4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailTextFieldres4.setForeground(new java.awt.Color(153, 255, 255));
        emailTextFieldres4.setBorder(null);
        emailTextFieldres4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldres4ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextFieldres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 300, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 51));
        jLabel12.setText("Reg. No.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, 30));

        roomnoTextFieldres4.setBackground(new java.awt.Color(0, 0, 51));
        roomnoTextFieldres4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnoTextFieldres4.setForeground(new java.awt.Color(153, 255, 255));
        roomnoTextFieldres4.setBorder(null);
        roomnoTextFieldres4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoTextFieldres4ActionPerformed(evt);
            }
        });
        jPanel1.add(roomnoTextFieldres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 60, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("Room No.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 110, 30));
        jPanel1.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 50, 10));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 270, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 153, 51));
        jLabel35.setText("Complaint");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 110, 30));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 110, 10));

        regnoTextFieldres5.setBackground(new java.awt.Color(0, 0, 51));
        regnoTextFieldres5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regnoTextFieldres5.setForeground(new java.awt.Color(153, 255, 255));
        regnoTextFieldres5.setBorder(null);
        regnoTextFieldres5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextFieldres5ActionPerformed(evt);
            }
        });
        jPanel1.add(regnoTextFieldres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 110, 30));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 110, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 51));
        jLabel14.setText("Hostel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 80, 30));

        hostelTextFieldres5.setBackground(new java.awt.Color(0, 0, 51));
        hostelTextFieldres5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostelTextFieldres5.setForeground(new java.awt.Color(153, 255, 255));
        hostelTextFieldres5.setBorder(null);
        hostelTextFieldres5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelTextFieldres5ActionPerformed(evt);
            }
        });
        jPanel1.add(hostelTextFieldres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 100, 30));

        emailTextFieldres5.setBackground(new java.awt.Color(0, 0, 51));
        emailTextFieldres5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailTextFieldres5.setForeground(new java.awt.Color(153, 255, 255));
        emailTextFieldres5.setBorder(null);
        emailTextFieldres5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldres5ActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextFieldres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 300, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 51));
        jLabel15.setText("Reg. No.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 110, 30));

        roomnoTextFieldres5.setBackground(new java.awt.Color(0, 0, 51));
        roomnoTextFieldres5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnoTextFieldres5.setForeground(new java.awt.Color(153, 255, 255));
        roomnoTextFieldres5.setBorder(null);
        roomnoTextFieldres5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoTextFieldres5ActionPerformed(evt);
            }
        });
        jPanel1.add(roomnoTextFieldres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 60, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 51));
        jLabel16.setText("Room No.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 110, 30));
        jPanel1.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 50, 10));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 270, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 153, 51));
        jLabel36.setText("Complaint");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomnoTextFieldres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoTextFieldres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoTextFieldres1ActionPerformed

    private void regnoTextFieldres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextFieldres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoTextFieldres1ActionPerformed

    private void hostelTextFieldres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelTextFieldres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostelTextFieldres1ActionPerformed

    private void emailTextFieldres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldres1ActionPerformed

    private void roomnoTextFieldres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoTextFieldres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoTextFieldres2ActionPerformed

    private void regnoTextFieldres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextFieldres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoTextFieldres2ActionPerformed

    private void hostelTextFieldres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelTextFieldres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostelTextFieldres2ActionPerformed

    private void emailTextFieldres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldres2ActionPerformed

    private void regnoTextFieldres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextFieldres3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoTextFieldres3ActionPerformed

    private void hostelTextFieldres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelTextFieldres3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostelTextFieldres3ActionPerformed

    private void emailTextFieldres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldres3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldres3ActionPerformed

    private void roomnoTextFieldres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoTextFieldres3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoTextFieldres3ActionPerformed

    private void regnoTextFieldres4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextFieldres4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoTextFieldres4ActionPerformed

    private void hostelTextFieldres4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelTextFieldres4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostelTextFieldres4ActionPerformed

    private void emailTextFieldres4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldres4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldres4ActionPerformed

    private void roomnoTextFieldres4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoTextFieldres4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoTextFieldres4ActionPerformed

    private void regnoTextFieldres5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextFieldres5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoTextFieldres5ActionPerformed

    private void hostelTextFieldres5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelTextFieldres5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostelTextFieldres5ActionPerformed

    private void emailTextFieldres5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldres5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldres5ActionPerformed

    private void roomnoTextFieldres5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoTextFieldres5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnoTextFieldres5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplainCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplainCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplainCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplainCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplainCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField emailTextFieldres1;
    public javax.swing.JTextField emailTextFieldres2;
    public javax.swing.JTextField emailTextFieldres3;
    public javax.swing.JTextField emailTextFieldres4;
    public javax.swing.JTextField emailTextFieldres5;
    public javax.swing.JTextField hostelTextFieldres1;
    public javax.swing.JTextField hostelTextFieldres2;
    public javax.swing.JTextField hostelTextFieldres3;
    public javax.swing.JTextField hostelTextFieldres4;
    public javax.swing.JTextField hostelTextFieldres5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField regnoTextFieldres1;
    public javax.swing.JTextField regnoTextFieldres2;
    public javax.swing.JTextField regnoTextFieldres3;
    public javax.swing.JTextField regnoTextFieldres4;
    public javax.swing.JTextField regnoTextFieldres5;
    public javax.swing.JTextField roomnoTextFieldres1;
    public javax.swing.JTextField roomnoTextFieldres2;
    public javax.swing.JTextField roomnoTextFieldres3;
    public javax.swing.JTextField roomnoTextFieldres4;
    public javax.swing.JTextField roomnoTextFieldres5;
    // End of variables declaration//GEN-END:variables
}
