/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.io.File;
import java.io.IOException;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author hp
 */
public class Information extends javax.swing.JFrame {

    /**
     * Creates new form Second
     */
    public Information() {
       
        initComponents();
         messinfor1.setVisible(false);
        complain.setVisible(false);
        information.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svbhoptions = new javax.swing.JPanel();
        information = new java.awt.Button();
        acadcalender = new java.awt.Button();
        hosteloption = new javax.swing.JComboBox<>();
        messinfor1 = new java.awt.Button();
        complain = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        alogin = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        svbhoptions.setBackground(new java.awt.Color(51, 51, 51));
        svbhoptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        information.setBackground(new java.awt.Color(255, 153, 51));
        information.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        information.setForeground(new java.awt.Color(0, 0, 0));
        information.setLabel("Information");
        information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationActionPerformed(evt);
            }
        });
        svbhoptions.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 290, 40));

        acadcalender.setBackground(new java.awt.Color(255, 153, 51));
        acadcalender.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        acadcalender.setForeground(new java.awt.Color(0, 0, 0));
        acadcalender.setLabel("Acadmic Calender");
        acadcalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acadcalenderActionPerformed(evt);
            }
        });
        svbhoptions.add(acadcalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 290, 40));

        hosteloption.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hosteloption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select hostel", "S.V.B.H.", "TILAK", "TANDON", "PATEL", "MALVIYA", "P.G. Boys" }));
        hosteloption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosteloptionActionPerformed(evt);
            }
        });
        svbhoptions.add(hosteloption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 290, 40));

        messinfor1.setBackground(new java.awt.Color(255, 153, 51));
        messinfor1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        messinfor1.setForeground(new java.awt.Color(0, 0, 0));
        messinfor1.setLabel("Mess Information");
        messinfor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messinfor1ActionPerformed(evt);
            }
        });
        svbhoptions.add(messinfor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 290, 40));

        complain.setBackground(new java.awt.Color(255, 153, 51));
        complain.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        complain.setForeground(new java.awt.Color(0, 0, 0));
        complain.setLabel("Complain section");
        complain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainActionPerformed(evt);
            }
        });
        svbhoptions.add(complain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 290, 40));

        getContentPane().add(svbhoptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 530, 620));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alogin.setBackground(new java.awt.Color(102, 153, 255));
        alogin.setFont(new java.awt.Font("Agency FB", 0, 26)); // NOI18N
        alogin.setForeground(new java.awt.Color(204, 255, 255));
        alogin.setLabel("Log in");
        alogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aloginActionPerformed(evt);
            }
        });
        jPanel2.add(alogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/MNNIT2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 310, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acadcalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acadcalenderActionPerformed
        // TODO add your handling code here:
       /* try
        {
            System.out.println("Worlds");
            String cmds[] = new String[] {"cmd", "/c", "images\\acadcal18.pdf"};
         //   java.lang.Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler" + "images\\acadcal18.pdf");
              java.lang.Runtime.getRuntime().exec(cmds);  
         System.out.println("Helo");
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }*/
       if (java.awt.Desktop.isDesktopSupported()) {
        try {
            File myFile = new File("C:\\Users\\hp\\Documents\\NetBeansProjects\\Project2\\src\\project2\\images\\acadcal18.pdf");
            java.awt.Desktop.getDesktop().open(myFile);
            } catch (IOException ex) {
        // no application registered for PDFs
                }
               }
    }//GEN-LAST:event_acadcalenderActionPerformed

    private void aloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aloginActionPerformed
        // TODO add your handling code here:
        AdminLogin al = new AdminLogin();
        al.setVisible(true);
        dispose();
    }//GEN-LAST:event_aloginActionPerformed

    private void complainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainActionPerformed
        // TODO add your handling code here:
        ComplainEntry ce = new ComplainEntry();
        ce.setVisible(true);
        dispose();
    }//GEN-LAST:event_complainActionPerformed
        PreparedStatement pstmt = null;
         ResultSet rs = null;
      
    private void messinfor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messinfor1ActionPerformed
        // TODO add your handling code here:
        MessInform mf = new MessInform();
        String jcom = hosteloption.getSelectedItem().toString();
        if(jcom.equals("S.V.B.H."))
        {
             try
                {
                    MySqlConnection my = new MySqlConnection();
                    //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from svbh_messinfo");
                   // pstmt.setString(1, reg);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        mf.jTextField22.setText(rs.getString("MessManager_name"));
                        mf.jTextField23.setText(rs.getString("MessManager_mobile"));
                        mf.jTextField1.setText(rs.getString("Mon_food_mor"));
                        mf.jTextField2.setText(rs.getString("Mon_food_afternoon"));
                        mf.jTextField3.setText(rs.getString("Mon_food_eve"));
                        mf.jTextField4.setText(rs.getString("Tue_food_mor"));
                        mf.jTextField5.setText(rs.getString("Tue_food_afternoon"));
                        mf.jTextField6.setText(rs.getString("Tue_food_eve"));
                        mf.jTextField7.setText(rs.getString("Wed_food_mor"));
                        mf.jTextField8.setText(rs.getString("Wed_food_afternoon"));
                        mf.jTextField9.setText(rs.getString("Wed_food_eve"));
                        mf.jTextField10.setText(rs.getString("Thu_food_mor"));
                        mf.jTextField11.setText(rs.getString("Thu_food_afternoon"));
                        mf.jTextField12.setText(rs.getString("Thu_food_eve"));
                        mf.jTextField13.setText(rs.getString("Fri_food_mor"));
                        mf.jTextField14.setText(rs.getString("Fri_food_afternoon"));
                        mf.jTextField15.setText(rs.getString("Fri_food_eve]"));
                        mf.jTextField16.setText(rs.getString("Sat_food_mor"));
                        mf.jTextField17.setText(rs.getString("Sat_food_afternoon"));
                        mf.jTextField18.setText(rs.getString("Sat_food_eve"));
                        mf.jTextField19.setText(rs.getString("Sun_food_mor"));
                        mf.jTextField20.setText(rs.getString("Sun_food_afternoon"));
                        mf.jTextField21.setText(rs.getString("Sun_food_eve"));
                        
                        
                    }
                    mf.setVisible(true);
                    dispose();
                }
             catch(Exception e)
             {
                 System.out.println(e);
             }
        }
        else if(jcom.equals("TILAK"))
        {
           try
                {
                    MySqlConnection my = new MySqlConnection();
                    //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from tilak_messinfo");
                   // pstmt.setString(1, reg);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        mf.jTextField22.setText(rs.getString("MessManager_name"));
                        mf.jTextField23.setText(rs.getString("MessManager_phone"));
                        mf.jTextField1.setText(rs.getString("Mon_food_mor"));
                        mf.jTextField2.setText(rs.getString("Mon_food_afternoon"));
                        mf.jTextField3.setText(rs.getString("Mon_food_eve"));
                        mf.jTextField4.setText(rs.getString("Tue_food_mor"));
                        mf.jTextField5.setText(rs.getString("Tue_food_afternoon"));
                        mf.jTextField6.setText(rs.getString("Tue_food_eve"));
                        mf.jTextField7.setText(rs.getString("Wed_food_mor"));
                        mf.jTextField8.setText(rs.getString("Wed_food_afternoon"));
                        mf.jTextField9.setText(rs.getString("Wed_food_eve"));
                        mf.jTextField10.setText(rs.getString("Thu_food_mor"));
                        mf.jTextField11.setText(rs.getString("Thu_food_afternoon"));
                        mf.jTextField12.setText(rs.getString("Thu_food_eve"));
                        mf.jTextField13.setText(rs.getString("Fri_food_mor"));
                        mf.jTextField14.setText(rs.getString("Fri_food_afternoon"));
                        mf.jTextField15.setText(rs.getString("Fri_food_eve"));
                        mf.jTextField16.setText(rs.getString("Sat_food_mor"));
                        mf.jTextField17.setText(rs.getString("Sat_food_afternoon"));
                        mf.jTextField18.setText(rs.getString("Sat_food_eve"));
                        mf.jTextField19.setText(rs.getString("Sun_food_mor"));
                        mf.jTextField20.setText(rs.getString("Sun_food_afternoon"));
                        mf.jTextField21.setText(rs.getString("Sun_food_eve"));
                        
                        
                    }
                    mf.setVisible(true);
                    dispose();
                }
             catch(Exception e)
             {
                 System.out.println(e);
             }
        
        }
    }//GEN-LAST:event_messinfor1ActionPerformed

    private void hosteloptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosteloptionActionPerformed
        // TODO add your handling code here:
       messinfor1.setVisible(true);
        complain.setVisible(true);
        information.setVisible(true); 
    }//GEN-LAST:event_hosteloptionActionPerformed

    private void informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationActionPerformed
        // TODO add your handling code here:
        WardenInfo wi = new WardenInfo();
        String jcom = hosteloption.getSelectedItem().toString();
        if(jcom.equals("S.V.B.H."))
        {
             try
                {
                    MySqlConnection my = new MySqlConnection();
                    //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from svbh_information");
                   // pstmt.setString(1, reg);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        
                        wi.jTextField1.setText(rs.getString("Warden_name"));
                        wi.jTextField2.setText(rs.getString("Warden_phone"));
                        wi.jTextField3.setText(rs.getString("Warden_Email"));
                        wi.jTextField4.setText(rs.getString("CareTaker_name"));
                        wi.jTextField5.setText(rs.getString("CareTaker_phone"));
                        wi.jTextField6.setText(rs.getString("CareTaker_Email"));
                        wi.jTextField7.setText(rs.getString("Hostelmanager_name"));
                        wi.jTextField8.setText(rs.getString("Hostel_manager_phone"));
                        wi.jTextField9.setText(rs.getString("Hostel_manager_email"));
                        
                        
                    }
                    wi.setVisible(true);
                    dispose();
                }
             catch(Exception e)
             {
                 System.out.println(e);
             }
        }
        else if(jcom.equals("TILAK"))
        {
             try
                {
                    MySqlConnection my = new MySqlConnection();
                    //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from tilak_information");
                   // pstmt.setString(1, reg);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        
                        wi.jTextField1.setText(rs.getString("Warden_name"));
                        wi.jTextField2.setText(rs.getString("Warden_phone"));
                        wi.jTextField3.setText(rs.getString("Warden_Email"));
                        wi.jTextField4.setText(rs.getString("CareTaker_name"));
                        wi.jTextField5.setText(rs.getString("CareTaker_phone"));
                        wi.jTextField6.setText(rs.getString("Care_Taker_Email"));
                        wi.jTextField7.setText(rs.getString("Hostel_manager"));
                        wi.jTextField8.setText(rs.getString("Hostelmanager_phone"));
                        wi.jTextField9.setText(rs.getString("Hostelmanager_email"));
                        
                        
                    }
                    wi.setVisible(true);
                    dispose();
                }
             catch(Exception e)
             {
                 System.out.println(e);
             }
        }
    }//GEN-LAST:event_informationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button acadcalender;
    private java.awt.Button alogin;
    public static java.awt.Button complain;
    public javax.swing.JComboBox<String> hosteloption;
    public static java.awt.Button information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    public static java.awt.Button messinfor1;
    private javax.swing.JPanel svbhoptions;
    // End of variables declaration//GEN-END:variables
}
