/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        usertextfield = new javax.swing.JTextField();
        userseparator = new javax.swing.JSeparator();
        userlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        passwordseparator = new javax.swing.JSeparator();
        PasswordField = new javax.swing.JPasswordField();
        signinbutton = new java.awt.Button();
        usericon = new javax.swing.JLabel();
        usericon1 = new javax.swing.JLabel();
        hostelmgmt = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 531));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(0, 0, 0));
        LoginPanel.setForeground(new java.awt.Color(51, 204, 255));

        usertextfield.setBackground(new java.awt.Color(0, 0, 0));
        usertextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usertextfield.setForeground(new java.awt.Color(255, 255, 255));
        usertextfield.setBorder(null);
        usertextfield.setCaretColor(new java.awt.Color(255, 255, 255));
        usertextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextfieldActionPerformed(evt);
            }
        });

        userlabel.setBackground(new java.awt.Color(51, 51, 51));
        userlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userlabel.setForeground(new java.awt.Color(0, 255, 255));
        userlabel.setText("Username");

        passwordlabel.setBackground(new java.awt.Color(51, 51, 51));
        passwordlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(0, 255, 255));
        passwordlabel.setText("Password");

        PasswordField.setBackground(new java.awt.Color(0, 0, 0));
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setBorder(null);
        PasswordField.setCaretColor(new java.awt.Color(255, 255, 255));

        signinbutton.setBackground(new java.awt.Color(255, 51, 51));
        signinbutton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        signinbutton.setForeground(new java.awt.Color(255, 255, 255));
        signinbutton.setLabel("Sign in");
        signinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbuttonActionPerformed(evt);
            }
        });

        usericon.setBackground(new java.awt.Color(0, 0, 0));
        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Lock_26px_2.png"))); // NOI18N
        usericon.setText("jLabel1");

        usericon1.setBackground(new java.awt.Color(0, 0, 0));
        usericon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_User_Male_26px_2.png"))); // NOI18N
        usericon1.setText("jLabel1");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usericon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usericon1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginPanelLayout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userseparator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordseparator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 70, Short.MAX_VALUE)))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(usericon1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(usericon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginPanelLayout.createSequentialGroup()
                    .addGap(0, 115, Short.MAX_VALUE)
                    .addComponent(userlabel)
                    .addGap(10, 10, 10)
                    .addComponent(usertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addComponent(userseparator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(passwordlabel)
                    .addGap(10, 10, 10)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(passwordseparator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 116, Short.MAX_VALUE)))
        );

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 450, 531));

        hostelmgmt.setBackground(new java.awt.Color(0, 0, 0));
        hostelmgmt.setFont(new java.awt.Font("Lucida Fax", 0, 65)); // NOI18N
        hostelmgmt.setForeground(new java.awt.Color(255, 255, 255));
        hostelmgmt.setText("Hostel Management");
        getContentPane().add(hostelmgmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 680, 80));

        imagelabel.setBackground(new java.awt.Color(0, 0, 0));
        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/svbh3.jpg"))); // NOI18N
        imagelabel.setText("jLabel1");
        getContentPane().add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbuttonActionPerformed
        // TODO add your handling code here:
        String us=usertextfield.getText();
        String pass=PasswordField.getText();
        if(us.equals("username") && pass.equals("password"))
        {
            Information s = new Information();
            s.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid userid or password");
        }
    }//GEN-LAST:event_signinbuttonActionPerformed

    private void usertextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel hostelmgmt;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JSeparator passwordseparator;
    private java.awt.Button signinbutton;
    private javax.swing.JLabel usericon;
    private javax.swing.JLabel usericon1;
    private javax.swing.JLabel userlabel;
    private javax.swing.JSeparator userseparator;
    private javax.swing.JTextField usertextfield;
    // End of variables declaration//GEN-END:variables
}
