/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */
public class Searching extends javax.swing.JFrame {

    /**
     * Creates new form Six
     */
    public Searching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxsearch = new javax.swing.JComboBox<>();
        searchTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        searchbutton = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        ablocksearchbutton1 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Search by :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 170, -1));

        jComboBoxsearch.setBackground(new java.awt.Color(153, 255, 255));
        jComboBoxsearch.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jComboBoxsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Registration_No.", "Room_No.", "Name" }));
        jComboBoxsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 210, 40));

        searchTextField.setBackground(new java.awt.Color(51, 153, 255));
        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(51, 0, 51));
        searchTextField.setBorder(null);
        jPanel1.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 400, 40));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 400, 10));

        searchbutton.setBackground(new java.awt.Color(0, 0, 0));
        searchbutton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        searchbutton.setForeground(new java.awt.Color(255, 255, 102));
        searchbutton.setLabel("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1147, 293));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ablocksearchbutton1.setBackground(new java.awt.Color(51, 153, 255));
        ablocksearchbutton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ablocksearchbutton1.setForeground(new java.awt.Color(255, 255, 255));
        ablocksearchbutton1.setLabel("Admin Block");
        ablocksearchbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ablocksearchbutton1ActionPerformed(evt);
            }
        });
        jPanel2.add(ablocksearchbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/searchimg.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1150, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxsearchActionPerformed
        // TODO add your handling code here:
        String jcom = jComboBoxsearch.getSelectedItem().toString();
        if(jcom.equals("Name"))
        {
         searchTextField.setText("Enter First name(eg:-Ram)");   
        }
        else if(jcom.equals("Registration_No."))
        {
            searchTextField.setText("Enter Registration No.");
        }
        else if(jcom.equals("Room_No."))
        {
            searchTextField.setText("Enter Room No.");
        }
    }//GEN-LAST:event_jComboBoxsearchActionPerformed

    private void ablocksearchbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ablocksearchbutton1ActionPerformed
        // TODO add your handling code here:
        AdminBlock ab = new AdminBlock();
        ab.setVisible(true);
        dispose();
    }//GEN-LAST:event_ablocksearchbutton1ActionPerformed
         PreparedStatement pstmt = null;
         ResultSet rs = null;
       String reg=null,hostelname_get=null,roomvalue_get=null,firstname_get=null,middlename_get=null,lastname_get=null,email_get=null,phone_get=null,branch_get=null;
       int count=0;
    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        String jcom = jComboBoxsearch.getSelectedItem().toString();   //Retrieve value from JCombo Box
        
        System.out.println(jcom);
        if(jcom.equals("Registration_No."))
        {
            reg = searchTextField.getText();
             try
            {
                    MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo where Registration_No=?");  // select table into database
                    pstmt.setString(1, reg);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        hostelname_get= rs.getString("Hostel_Name");
                        roomvalue_get = rs.getString("Room_No");
                        firstname_get= rs.getString("First_Name");
                        middlename_get= rs.getString("Middle_Name");                     // retrieve valiue from database
                        lastname_get= rs.getString("Last_Name");
                        email_get= rs.getString("Email");
                        phone_get= rs.getString("Phone_No");
                        branch_get= rs.getString("Branch");
                    }
                    Result res = new Result();
                    if(middlename_get!=null)
                    {
                        res.nameTextFieldres1.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                    }
                    else
                    {
                        res.nameTextFieldres1.setText(firstname_get+" "+lastname_get);
                    }
                    res.roomnoTextFieldres1.setText(roomvalue_get);
                    res.emailTextFieldres1.setText(email_get);
                    res.mobilenoTextFieldres1.setText(phone_get);
                    res.regnoTextFieldres1.setText(reg);
                    res.hostelTextFieldres1.setText(hostelname_get);
                    res.branchTextFieldres1.setText(branch_get);
         
                    res.setVisible(true);
                    
                    
            }
            catch(SQLException e12)
            {
                    System.out.println(e12);
            }
        }
        else if(jcom.equals("Room_No."))
        {
            roomvalue_get=searchTextField.getText();
                try{
                    MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo where Room_No=?");
                    pstmt.setString(1, roomvalue_get);
                    rs = pstmt.executeQuery();
                    Result res = new Result();
                    while(rs.next())
                    {
                        count++;
                        reg= rs.getString("Registration_No");
                        hostelname_get= rs.getString("Hostel_Name");
                        roomvalue_get = rs.getString("Room_No");
                        firstname_get= rs.getString("First_Name");
                        middlename_get= rs.getString("Middle_Name");
                        lastname_get= rs.getString("Last_Name");
                        email_get= rs.getString("Email");
                        phone_get= rs.getString("Phone_No");
                        branch_get= rs.getString("Branch");
                        if(count==1)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres1.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres1.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres1.setText(roomvalue_get);
                                res.emailTextFieldres1.setText(email_get);
                                res.mobilenoTextFieldres1.setText(phone_get);
                                res.regnoTextFieldres1.setText(reg);
                                res.hostelTextFieldres1.setText(hostelname_get);
                                res.branchTextFieldres1.setText(branch_get);
                            
                        }
                        else if(count==2)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres2.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres2.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres2.setText(roomvalue_get);
                                res.emailTextFieldres2.setText(email_get);
                                res.mobilenoTextFieldres2.setText(phone_get);
                                res.regnoTextFieldres2.setText(reg);
                                res.hostelTextFieldres2.setText(hostelname_get);
                                res.branchTextFieldres2.setText(branch_get);
                        }
                        else if(count==3)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres3.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres3.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres3.setText(roomvalue_get);
                                res.emailTextFieldres3.setText(email_get);
                                res.mobilenoTextFieldres3.setText(phone_get);
                                res.regnoTextFieldres3.setText(reg);
                                res.hostelTextFieldres3.setText(hostelname_get);
                                res.branchTextFieldres3.setText(branch_get);
                        }
                       
                    }
                  //  System.out.println(count);
                    res.setVisible(true);
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                }
        }
        else if(jcom.equals("Name"))
        {
            firstname_get=searchTextField.getText();
                try{
                    MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo where First_Name=?");
                    pstmt.setString(1, firstname_get);
                    rs = pstmt.executeQuery();
                    Result res = new Result();
                    while(rs.next())
                    {
                        count++;
                        reg= rs.getString("Registration_No");
                        hostelname_get= rs.getString("Hostel_Name");
                        roomvalue_get = rs.getString("Room_No");
                        firstname_get= rs.getString("First_Name");
                        middlename_get= rs.getString("Middle_Name");
                        lastname_get= rs.getString("Last_Name");
                        email_get= rs.getString("Email");
                        phone_get= rs.getString("Phone_No");
                        branch_get= rs.getString("Branch");
                        if(count==1)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres1.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres1.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres1.setText(roomvalue_get);
                                res.emailTextFieldres1.setText(email_get);
                                res.mobilenoTextFieldres1.setText(phone_get);
                                res.regnoTextFieldres1.setText(reg);
                                res.hostelTextFieldres1.setText(hostelname_get);
                                res.branchTextFieldres1.setText(branch_get);
                            
                        }
                        else if(count==2)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres2.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres2.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres2.setText(roomvalue_get);
                                res.emailTextFieldres2.setText(email_get);
                                res.mobilenoTextFieldres2.setText(phone_get);
                                res.regnoTextFieldres2.setText(reg);
                                res.hostelTextFieldres2.setText(hostelname_get);
                                res.branchTextFieldres2.setText(branch_get);
                        }
                        else if(count==3)
                        {
                            
                            if(middlename_get!=null)
                            {
                                res.nameTextFieldres3.setText(firstname_get+" "+middlename_get+" "+lastname_get);
                            }
                            else
                            {
                                res.nameTextFieldres3.setText(firstname_get+" "+lastname_get);
                            }
                                res.roomnoTextFieldres3.setText(roomvalue_get);
                                res.emailTextFieldres3.setText(email_get);
                                res.mobilenoTextFieldres3.setText(phone_get);
                                res.regnoTextFieldres3.setText(reg);
                                res.hostelTextFieldres3.setText(hostelname_get);
                                res.branchTextFieldres3.setText(branch_get);
                        }
                       
                    }
                  //  System.out.println(count);
                    res.setVisible(true);
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                }
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ablocksearchbutton1;
    private javax.swing.JComboBox<String> jComboBoxsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField searchTextField;
    private java.awt.Button searchbutton;
    // End of variables declaration//GEN-END:variables
}
