/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Signup = new javax.swing.JPanel();
        masterpasswordlabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        userlabel = new javax.swing.JLabel();
        usertextfield = new javax.swing.JTextField();
        signupbutton = new java.awt.Button();
        newpasswordlabel = new javax.swing.JLabel();
        confirmpasswordlabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        masterPasswordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Signup.setBackground(new java.awt.Color(0, 0, 0));

        masterpasswordlabel.setBackground(new java.awt.Color(51, 51, 51));
        masterpasswordlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        masterpasswordlabel.setForeground(new java.awt.Color(0, 255, 255));
        masterpasswordlabel.setText("Admin Password");

        newPasswordField.setBackground(new java.awt.Color(0, 0, 0));
        newPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordField.setBorder(null);
        newPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));

        userlabel.setBackground(new java.awt.Color(51, 51, 51));
        userlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userlabel.setForeground(new java.awt.Color(0, 255, 255));
        userlabel.setText("Username");

        usertextfield.setBackground(new java.awt.Color(0, 0, 0));
        usertextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usertextfield.setForeground(new java.awt.Color(255, 255, 255));
        usertextfield.setBorder(null);
        usertextfield.setCaretColor(new java.awt.Color(255, 255, 255));
        usertextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextfieldActionPerformed(evt);
            }
        });

        signupbutton.setBackground(new java.awt.Color(255, 51, 51));
        signupbutton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(255, 255, 255));
        signupbutton.setLabel("Sign up");
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });

        newpasswordlabel.setBackground(new java.awt.Color(51, 51, 51));
        newpasswordlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        newpasswordlabel.setForeground(new java.awt.Color(0, 255, 255));
        newpasswordlabel.setText("New Password");

        confirmpasswordlabel.setBackground(new java.awt.Color(51, 51, 51));
        confirmpasswordlabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        confirmpasswordlabel.setForeground(new java.awt.Color(0, 255, 255));
        confirmpasswordlabel.setText("Confirm Password");

        confirmPasswordField.setBackground(new java.awt.Color(0, 0, 0));
        confirmPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordField.setBorder(null);
        confirmPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));

        masterPasswordField.setBackground(new java.awt.Color(0, 0, 0));
        masterPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        masterPasswordField.setBorder(null);
        masterPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Padlock_26px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Lock_26px_2.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_User_Male_26px_2.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/icons8_Lock_26px_2.png"))); // NOI18N
        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout SignupLayout = new javax.swing.GroupLayout(Signup);
        Signup.setLayout(SignupLayout);
        SignupLayout.setHorizontalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupLayout.createSequentialGroup()
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addComponent(masterPasswordField)
                    .addComponent(confirmPasswordField)
                    .addComponent(signupbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(confirmpasswordlabel)
                    .addComponent(newpasswordlabel)
                    .addComponent(newPasswordField)
                    .addComponent(masterpasswordlabel)
                    .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usertextfield)
                    .addComponent(jSeparator2))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        SignupLayout.setVerticalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(userlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addComponent(usertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addComponent(masterpasswordlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(newpasswordlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(confirmpasswordlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(signupbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project2/images/signup.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextfieldActionPerformed
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        
    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        String uname = usertextfield.getText();
        String mpass = masterPasswordField.getText();
        String newpass = newPasswordField.getText();
        String confpass = confirmPasswordField.getText();
        String adpass=null;
        System.out.println(newpass);
        System.out.println(confpass);
        if(newpass.equals(confpass))
        {
            try
            {
                MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                pstmt = MySqlConnection.conn.prepareStatement("select * from hostelmgmt.administrative where userid=?");
                pstmt.setString(1, uname);
                rs = pstmt.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Username already registered..!!");
                }
                else
                {
                    pstmt.setString(1, "admin");
                    rs= pstmt.executeQuery();
                    while(rs.next())
                    {
                        adpass = rs.getString("password");
                    }
                    if(mpass.equals(adpass))
                    {
                        pstmt = MySqlConnection.conn.prepareStatement("insert into hostelmgmt.administrative (userid,password) values('"+uname+"','"+newpass+"')");
                        int i= pstmt.executeUpdate();
                        if(i>0)
                        {
                            JOptionPane.showMessageDialog(null, "New admin account is created succesfully");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Admin account is not created........");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "You must have permitted to admin....!!");
                    }
                }
            /* while(rs.next())
            {
            roomvalue = rs.getString("Room_No");
            firstnamereg.setText(rs.getString("First_Name"));
            
            }*/
           
            }
            catch(SQLException e12)
            {
                System.out.println(e12);
            }
        }
        else
        {
          JOptionPane.showMessageDialog(null, "new password and confirm password is not matched...!!");
        }
    }//GEN-LAST:event_signupbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Signup;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmpasswordlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField masterPasswordField;
    private javax.swing.JLabel masterpasswordlabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newpasswordlabel;
    private java.awt.Button signupbutton;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField usertextfield;
    // End of variables declaration//GEN-END:variables
}
