/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SroomAllot extends javax.swing.JFrame {

    /**
     * Creates new form Five
     */
    public SroomAllot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        roomnotextfieldreg = new javax.swing.JTextField();
        userlabel1 = new javax.swing.JLabel();
        userlabel2 = new javax.swing.JLabel();
        userlabel3 = new javax.swing.JLabel();
        lastnamereg = new javax.swing.JTextField();
        middlenamereg = new javax.swing.JTextField();
        userlabel4 = new javax.swing.JLabel();
        registrationnoreg = new javax.swing.JTextField();
        userlabel5 = new javax.swing.JLabel();
        branchreg = new javax.swing.JTextField();
        userlabel6 = new javax.swing.JLabel();
        emailreg = new javax.swing.JTextField();
        userlabel7 = new javax.swing.JLabel();
        ablockreg = new java.awt.Button();
        checkreg = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        firstnamereg = new javax.swing.JTextField();
        userlabel8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        userlabel9 = new javax.swing.JLabel();
        mobilenoreg1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        submitreg1 = new java.awt.Button();
        userlabel10 = new javax.swing.JLabel();
        hosteloption = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlabel.setBackground(new java.awt.Color(51, 51, 51));
        userlabel.setFont(new java.awt.Font("Agency FB", 0, 70)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 204, 51));
        userlabel.setText("Student Room Allot");
        jPanel1.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 490, 90));

        roomnotextfieldreg.setBackground(new java.awt.Color(0, 0, 0));
        roomnotextfieldreg.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        roomnotextfieldreg.setForeground(new java.awt.Color(255, 153, 51));
        roomnotextfieldreg.setBorder(null);
        roomnotextfieldreg.setCaretColor(new java.awt.Color(255, 255, 255));
        roomnotextfieldreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnotextfieldregActionPerformed(evt);
            }
        });
        jPanel1.add(roomnotextfieldreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 100, 40));

        userlabel1.setBackground(new java.awt.Color(51, 51, 51));
        userlabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userlabel1.setForeground(new java.awt.Color(0, 255, 255));
        userlabel1.setText("First Name");
        jPanel1.add(userlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, -1));

        userlabel2.setBackground(new java.awt.Color(51, 51, 51));
        userlabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userlabel2.setForeground(new java.awt.Color(0, 255, 255));
        userlabel2.setText("Middle Name");
        jPanel1.add(userlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 104, -1));

        userlabel3.setBackground(new java.awt.Color(51, 51, 51));
        userlabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userlabel3.setForeground(new java.awt.Color(0, 255, 255));
        userlabel3.setText("Last Name");
        jPanel1.add(userlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 80, -1));

        lastnamereg.setBackground(new java.awt.Color(0, 0, 0));
        lastnamereg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastnamereg.setForeground(new java.awt.Color(255, 255, 255));
        lastnamereg.setBorder(null);
        lastnamereg.setCaretColor(new java.awt.Color(255, 255, 255));
        lastnamereg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameregActionPerformed(evt);
            }
        });
        jPanel1.add(lastnamereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 242, 33));

        middlenamereg.setBackground(new java.awt.Color(0, 0, 0));
        middlenamereg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        middlenamereg.setForeground(new java.awt.Color(255, 255, 255));
        middlenamereg.setBorder(null);
        middlenamereg.setCaretColor(new java.awt.Color(255, 255, 255));
        middlenamereg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameregActionPerformed(evt);
            }
        });
        jPanel1.add(middlenamereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 242, 34));

        userlabel4.setBackground(new java.awt.Color(51, 51, 51));
        userlabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        userlabel4.setForeground(new java.awt.Color(0, 255, 255));
        userlabel4.setText("Registration No.");
        jPanel1.add(userlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        registrationnoreg.setBackground(new java.awt.Color(0, 0, 0));
        registrationnoreg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        registrationnoreg.setForeground(new java.awt.Color(255, 153, 51));
        registrationnoreg.setBorder(null);
        registrationnoreg.setCaretColor(new java.awt.Color(255, 255, 255));
        registrationnoreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationnoregActionPerformed(evt);
            }
        });
        jPanel1.add(registrationnoreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 200, 40));

        userlabel5.setBackground(new java.awt.Color(51, 51, 51));
        userlabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userlabel5.setForeground(new java.awt.Color(0, 255, 255));
        userlabel5.setText("Mobile");
        jPanel1.add(userlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        branchreg.setBackground(new java.awt.Color(0, 0, 0));
        branchreg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branchreg.setForeground(new java.awt.Color(255, 255, 255));
        branchreg.setBorder(null);
        branchreg.setCaretColor(new java.awt.Color(255, 255, 255));
        branchreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchregActionPerformed(evt);
            }
        });
        jPanel1.add(branchreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 220, 30));

        userlabel6.setBackground(new java.awt.Color(51, 51, 51));
        userlabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userlabel6.setForeground(new java.awt.Color(0, 255, 255));
        userlabel6.setText("Email");
        jPanel1.add(userlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        emailreg.setBackground(new java.awt.Color(0, 0, 0));
        emailreg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailreg.setForeground(new java.awt.Color(255, 255, 255));
        emailreg.setBorder(null);
        emailreg.setCaretColor(new java.awt.Color(255, 255, 255));
        emailreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailregActionPerformed(evt);
            }
        });
        jPanel1.add(emailreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 261, 30));

        userlabel7.setBackground(new java.awt.Color(51, 51, 51));
        userlabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userlabel7.setForeground(new java.awt.Color(0, 255, 255));
        userlabel7.setText("Hostel");
        jPanel1.add(userlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        ablockreg.setBackground(new java.awt.Color(0, 0, 0));
        ablockreg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ablockreg.setForeground(new java.awt.Color(255, 51, 153));
        ablockreg.setLabel("Admin Block");
        ablockreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ablockregActionPerformed(evt);
            }
        });
        jPanel1.add(ablockreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 140, 40));

        checkreg.setBackground(new java.awt.Color(0, 0, 0));
        checkreg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkreg.setForeground(new java.awt.Color(0, 255, 255));
        checkreg.setLabel("check");
        checkreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkregActionPerformed(evt);
            }
        });
        jPanel1.add(checkreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 240, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 240, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 210, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 272, 210, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 270, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 332, 250, 10));

        firstnamereg.setBackground(new java.awt.Color(0, 0, 0));
        firstnamereg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstnamereg.setForeground(new java.awt.Color(255, 255, 255));
        firstnamereg.setBorder(null);
        firstnamereg.setCaretColor(new java.awt.Color(255, 255, 255));
        firstnamereg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameregActionPerformed(evt);
            }
        });
        jPanel1.add(firstnamereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 242, 30));

        userlabel8.setBackground(new java.awt.Color(51, 51, 51));
        userlabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userlabel8.setForeground(new java.awt.Color(0, 255, 255));
        userlabel8.setText("Name");
        jPanel1.add(userlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 100, 10));

        userlabel9.setBackground(new java.awt.Color(51, 51, 51));
        userlabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        userlabel9.setForeground(new java.awt.Color(0, 255, 255));
        userlabel9.setText("Room No :");
        jPanel1.add(userlabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 150, 40));

        mobilenoreg1.setBackground(new java.awt.Color(0, 0, 0));
        mobilenoreg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobilenoreg1.setForeground(new java.awt.Color(255, 255, 255));
        mobilenoreg1.setBorder(null);
        mobilenoreg1.setCaretColor(new java.awt.Color(255, 255, 255));
        mobilenoreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoreg1ActionPerformed(evt);
            }
        });
        jPanel1.add(mobilenoreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 261, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 240, 10));

        submitreg1.setBackground(new java.awt.Color(0, 0, 0));
        submitreg1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitreg1.setForeground(new java.awt.Color(0, 255, 255));
        submitreg1.setLabel("Submit");
        submitreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitreg1ActionPerformed(evt);
            }
        });
        jPanel1.add(submitreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 120, 40));

        userlabel10.setBackground(new java.awt.Color(51, 51, 51));
        userlabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userlabel10.setForeground(new java.awt.Color(0, 255, 255));
        userlabel10.setText("Branch");
        jPanel1.add(userlabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));

        hosteloption.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hosteloption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select hostel", "S.V.B.H.", "TILAK", "TANDON", "PATEL", "MALVIYA", "P.G. Boys" }));
        jPanel1.add(hosteloption, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomnotextfieldregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnotextfieldregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnotextfieldregActionPerformed

    private void lastnameregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameregActionPerformed

    private void middlenameregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameregActionPerformed

    private void registrationnoregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationnoregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationnoregActionPerformed

    private void branchregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchregActionPerformed

    private void emailregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailregActionPerformed

    private void firstnameregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameregActionPerformed

    private void mobilenoreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoreg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenoreg1ActionPerformed
        String roomvalue;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        String reg=null;
        
    private void checkregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkregActionPerformed
        // TODO add your handling code here:
        reg = registrationnoreg.getText();
       // String CONN_STRING="jdbc:mysql://localhost:3306/hostelmgmt";
       // Connection conn = null;
        
        try
        {
            MySqlConnection my = new MySqlConnection(); //Start database connection
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
            pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo where Registration_No=?"); //Prepared database statement
            pstmt.setString(1, reg); //
            rs = pstmt.executeQuery(); //Statement for execution querry
            while(rs.next())
            {
                roomvalue = rs.getString("Room_No");
                firstnamereg.setText(rs.getString("First_Name"));
                middlenamereg.setText(rs.getString("Middle_Name"));             //Retrieve value from Database
                lastnamereg.setText(rs.getString("Last_Name"));
                emailreg.setText(rs.getString("Email"));
                mobilenoreg1.setText(rs.getString("Phone_No"));
                branchreg.setText(rs.getString("Branch"));
            }
        }
        catch(SQLException e12)
        {
            System.out.println(e12);
        }
        
        
    }//GEN-LAST:event_checkregActionPerformed
        
    private void submitreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitreg1ActionPerformed
        // TODO add your handling code here:
       int count=0;
        try
        {
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
            
            System.out.println(roomvalue);
            if(roomvalue==null)
            {
                String roomvalue1 = roomnotextfieldreg.getText();  
                String jbox = hosteloption.getSelectedItem().toString();       //Retrieve value from JCombo BOx
                reg = registrationnoreg.getText();
               
                try{
                   // MySqlConnection my = new MySqlConnection();
         //   conn = DriverManager.getConnection(CONN_STRING,"root","sony");
                    pstmt = MySqlConnection.conn.prepareStatement("select * from studentinfo where Room_No=?");
                    pstmt.setString(1, roomvalue1);
                    rs = pstmt.executeQuery();
                    while(rs.next())
                    {
                        count++;
                    }
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                if(count<3)
                {
                String sql = "update hostelmgmt.studentinfo SET Hostel_Name='"+jbox+"', Room_No='"+roomvalue1+"' where Registration_No='"+reg+"'";  
                pstmt = MySqlConnection.conn.prepareStatement(sql);   //Update Hostel name and room no. into Database
             //   pstmt.setString(1, reg);
          
              //  pstmt.setString(2, jbox);
              //  pstmt.setString(3, roomvalue1); 
                // pstmt = MySqlConnection.conn.prepareStatement("INSERT INTO 'hostelmgmt'.'studentinfo'('Room_No','Hostel_Name') VALUES ('"+roomvalue+"','"+jbox+"')");
                // Statement stmt = (Statement) MySqlConnection.conn.createStatement();
              //  String insert = "INSERT INTO 'hostelmgmt'.'studentinfo'('Room_No','Hostel_Name') VALUES ('+roomvalue+','+jbox+')";
              //  stmt.executeUpdate(insert);
                int i= pstmt.executeUpdate();
          //    System.out.println(jbox);
           //  System.out.println(roomvalue1);
                if(i>0)
                {
                        JOptionPane.showMessageDialog(null, "Data is saved in database");
                }
                else
                {
                        JOptionPane.showMessageDialog(null, "Data is not saved in database");
                }
                }
                else
                {
                         JOptionPane.showMessageDialog(null, "There is not available any bed in this Room_No.");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Already alloted Room for this student...!!");
            }
            
        }
        catch(SQLException e12)
        {
            System.out.println(e12);
        }
  /*      finally
        {
            try
            {
                MySqlConnection.conn.close();
              
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
        }*/
    }//GEN-LAST:event_submitreg1ActionPerformed

    private void ablockregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ablockregActionPerformed
        // TODO add your handling code here:
        AdminBlock ad = new AdminBlock();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_ablockregActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SroomAllot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SroomAllot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SroomAllot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SroomAllot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SroomAllot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button ablockreg;
    private javax.swing.JTextField branchreg;
    private java.awt.Button checkreg;
    private javax.swing.JTextField emailreg;
    private javax.swing.JTextField firstnamereg;
    private javax.swing.JComboBox<String> hosteloption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastnamereg;
    private javax.swing.JTextField middlenamereg;
    private javax.swing.JTextField mobilenoreg1;
    private javax.swing.JTextField registrationnoreg;
    private javax.swing.JTextField roomnotextfieldreg;
    private java.awt.Button submitreg1;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel userlabel1;
    private javax.swing.JLabel userlabel10;
    private javax.swing.JLabel userlabel2;
    private javax.swing.JLabel userlabel3;
    private javax.swing.JLabel userlabel4;
    private javax.swing.JLabel userlabel5;
    private javax.swing.JLabel userlabel6;
    private javax.swing.JLabel userlabel7;
    private javax.swing.JLabel userlabel8;
    private javax.swing.JLabel userlabel9;
    // End of variables declaration//GEN-END:variables
}
